
# * This file is designed to be used in Test to make sure we don't add cargo_dependencies twice.

[package]
name = "cli_coming_soon"
version = "0.0.5"
edition = "2021"
description = "A CLI tool to add components to your app"
authors = ["Everlabs"]
license = "MIT"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
colored = "2.1.0"
indicatif = "0.17.8"
codee = "0.3.0"
convert_case = "0.8.0"
ev = "0.1.0"
unic-langid = "0.9.5"



[[bin]]
name = "cli_coming_soon"
path = "src/main.rs"
